# Generated by Django 3.0.14 on 2022-05-29 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frm1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Не менее двух букв')])),
                ('number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10, 'Не менее десяти цифр')])),
                ('comms', models.TextField()),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
