# Generated by Django 3.0.14 on 2022-06-09 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frm1',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frm1',
            name='tip',
            field=models.CharField(choices=[('POLI', 'Поликарбонат'), ('METAL', 'Металлопрофиль'), ('MONO', 'Монолит'), ('SOFT', 'Мягкая кровля'), ('DEREVO', 'Дерево'), ('PROFIL', 'Профильная труба'), ('METCHER', 'Металлочерепица'), ('KOVK', 'Ковка')], default='POLI', max_length=20),
        ),
        migrations.AddField(
            model_name='frm1',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frm1',
            name='number',
            field=models.PositiveIntegerField(max_length=20, validators=[django.core.validators.MinLengthValidator(10, 'Не менее десяти цифр')]),
        ),
    ]
