# Generated by Django 3.0.14 on 2022-06-09 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220609_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frm1',
            name='comms',
        ),
        migrations.RemoveField(
            model_name='frm1',
            name='length',
        ),
        migrations.RemoveField(
            model_name='frm1',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='frm1',
            name='width',
        ),
        migrations.AlterField(
            model_name='frm1',
            name='number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10, 'Не менее десяти цифр')]),
        ),
    ]
