# Generated by Django 3.0.14 on 2022-06-09 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220609_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='frm2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Не менее двух букв')])),
                ('number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10, 'Не менее десяти цифр')])),
                ('sent', models.BooleanField(default=False)),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('tip', models.CharField(choices=[('POLI', 'Поликарбонат'), ('METAL', 'Металлопрофиль'), ('MONO', 'Монолит'), ('SOFT', 'Мягкая кровля'), ('DEREVO', 'Дерево'), ('PROFIL', 'Профильная труба'), ('METCHER', 'Металлочерепица'), ('KOVK', 'Ковка')], default='POLI', max_length=20)),
            ],
        ),
    ]
