# Generated by Django 3.0.14 on 2022-06-10 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220609_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='newfrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10, 'Не менее десяти цифр')])),
                ('sent', models.BooleanField(default=False)),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('tip', models.CharField(choices=[('POLI', 'Поликарбонат'), ('METAL', 'Металлопрофиль'), ('MONO', 'Монолит'), ('SOFT', 'Мягкая кровля'), ('DEREVO', 'Дерево'), ('PROFIL', 'Профильная труба'), ('METCHER', 'Металлочерепица'), ('KOVK', 'Ковка')], default='POLI', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='frm2',
            name='name',
            field=models.CharField(default=0, max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Не менее двух букв')]),
            preserve_default=False,
        ),
    ]
