# Generated by Django 3.0.14 on 2022-06-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_newfrm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfrm',
            name='length',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='newfrm',
            name='width',
            field=models.CharField(max_length=20),
        ),
    ]
