# Generated by Django 3.0.14 on 2022-06-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220610_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frm2',
            name='name',
        ),
    ]
