# Generated by Django 3.0.14 on 2022-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_frm2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frm2',
            name='tip',
            field=models.CharField(choices=[('Поликарбонат', 'Поликарбонат'), ('Металлопрофиль', 'Металлопрофиль'), ('Монолит', 'Монолит'), ('Мягкая кровля', 'Мягкая кровля'), ('Дерево', 'Дерево'), ('Профильная труба', 'Профильная труба'), ('Металлочерепица', 'Металлочерепица'), ('Ковка', 'Ковка')], default='POLI', max_length=40),
        ),
    ]
